import CoreLocation
import XCTest
@testable import otto_mobile

final class RouteAutoPathPointGeneratorTests: XCTestCase {
    func testProjectsTurnCoordinatesWithinFinishBuffer() {
        let corner = CLLocationCoordinate2D(latitude: 37.0, longitude: -122.0)
        let line = [
            CLLocationCoordinate2D(latitude: 37.0, longitude: -122.02),
            corner,
            CLLocationCoordinate2D(latitude: 37.02, longitude: -122.0),
        ]

        let generated = RouteAutoPathPointGenerator.autoTurnPathCoordinates(
            turnCoordinates: [corner],
            roadCoordinates: line
        )

        XCTAssertEqual(generated.count, 1)
        guard let projection = RouteMapGeometry.projectOntoPolyline(generated[0], onto: line) else {
            return XCTFail("Expected projection")
        }
        guard let cornerProjection = RouteMapGeometry.projectOntoPolyline(corner, onto: line) else {
            return XCTFail("Expected corner projection")
        }
        XCTAssertEqual(projection.arcLengthMeters, cornerProjection.arcLengthMeters, accuracy: 1)
    }

    func testExcludesTurnsNearStartAndFinish() {
        let start = CLLocationCoordinate2D(latitude: 37.0, longitude: -122.0)
        let finish = CLLocationCoordinate2D(latitude: 37.05, longitude: -122.0)
        let line = [start, finish]

        let generated = RouteAutoPathPointGenerator.autoTurnPathCoordinates(
            turnCoordinates: [start, finish],
            roadCoordinates: line
        )

        XCTAssertTrue(generated.isEmpty)
    }

    func testSyncPreservesManualPathPoints() {
        let manualCoordinate = CLLocationCoordinate2D(latitude: 37.01, longitude: -122.0)
        let autoCoordinate = CLLocationCoordinate2D(latitude: 37.02, longitude: -122.0)
        let existing: [RouteBuilderPointProxy] = [
            .init(type: .start, isAutoGenerated: false),
            .init(type: .path, coordinate: manualCoordinate, isAutoGenerated: false),
            .init(type: .path, coordinate: autoCoordinate, isAutoGenerated: true),
            .init(type: .finish, isAutoGenerated: false),
        ]

        let synced = RouteBuilderPointProxy.syncAutoPathPoints(
            existing: existing,
            autoCoordinates: [CLLocationCoordinate2D(latitude: 37.03, longitude: -122.0)]
        )

        XCTAssertEqual(synced.filter { $0.type == .path && !$0.isAutoGenerated }.count, 1)
        XCTAssertEqual(synced.filter { $0.type == .path && $0.isAutoGenerated }.count, 1)
        XCTAssertEqual(
            synced.first(where: { $0.type == .path && !$0.isAutoGenerated })?.coordinate.latitude ?? 0,
            manualCoordinate.latitude,
            accuracy: 0.00001
        )
    }
}

private struct RouteBuilderPointProxy {
    enum PointType {
        case start
        case path
        case finish
    }

    let type: PointType
    let coordinate: CLLocationCoordinate2D
    let isAutoGenerated: Bool

    init(type: PointType, coordinate: CLLocationCoordinate2D = .init(), isAutoGenerated: Bool) {
        self.type = type
        self.coordinate = coordinate
        self.isAutoGenerated = isAutoGenerated
    }

    static func syncAutoPathPoints(
        existing: [RouteBuilderPointProxy],
        autoCoordinates: [CLLocationCoordinate2D]
    ) -> [RouteBuilderPointProxy] {
        let preserved = existing.filter { !($0.type == .path && $0.isAutoGenerated) }
        let autoPoints = autoCoordinates.map {
            RouteBuilderPointProxy(type: .path, coordinate: $0, isAutoGenerated: true)
        }
        return preserved + autoPoints
    }
}
