import XCTest
@testable import otto_mobile

final class RouteBuilderPointRoutingTests: XCTestCase {
    func testAutoShapeDoesNotAffectRoutingByDefault() {
        let autoShapeID = UUID()
        XCTAssertFalse(
            RouteBuilderPointRoutingProxy(
                type: .path,
                isAutoGenerated: true,
                id: autoShapeID
            ).affectsRouting()
        )
    }

    func testAutoShapeAffectsRoutingWhileDragging() {
        let autoShapeID = UUID()
        let point = RouteBuilderPointRoutingProxy(
            type: .path,
            isAutoGenerated: true,
            id: autoShapeID
        )
        XCTAssertTrue(point.affectsRouting(activeDragPointID: autoShapeID))
        XCTAssertFalse(point.affectsRouting(activeDragPointID: UUID()))
    }

    func testUserPathAffectsRouting() {
        XCTAssertTrue(
            RouteBuilderPointRoutingProxy(type: .path, isAutoGenerated: false).affectsRouting()
        )
    }

    func testWaypointDoesNotAffectRouting() {
        XCTAssertFalse(
            RouteBuilderPointRoutingProxy(type: .waypoint, isAutoGenerated: false).affectsRouting()
        )
    }

    func testLockedEndpointsAffectRouting() {
        XCTAssertTrue(RouteBuilderPointRoutingProxy(type: .start).affectsRouting())
        XCTAssertTrue(RouteBuilderPointRoutingProxy(type: .finish).affectsRouting())
    }

    func testStopDoesNotAffectRouting() {
        XCTAssertFalse(RouteBuilderPointRoutingProxy(type: .stop).affectsRouting())
    }

    func testAutoShapeDragStaysAutoGenerated() {
        let originalID = UUID()
        let moved = RouteBuilderPointRoutingProxy.moveAutoShape(
            originalID: originalID,
            newCoordinate: (37.1, -122.1)
        )
        XCTAssertTrue(moved.isAutoShape)
        XCTAssertTrue(moved.isAutoGenerated)
    }

    func testUserPathMoveStaysUserSourced() {
        let originalID = UUID()
        let moved = RouteBuilderPointRoutingProxy.moveUserPath(
            originalID: originalID,
            newCoordinate: (37.1, -122.1)
        )
        XCTAssertFalse(moved.isAutoShape)
        XCTAssertFalse(moved.isAutoGenerated)
    }

    func testSyncAutoPathPointsDropsAutoShapeAndRegenerates() {
        let manual = RouteBuilderPointRoutingProxy(type: .path, isAutoGenerated: false)
        let staleAuto = RouteBuilderPointRoutingProxy(type: .path, isAutoGenerated: true)
        let start = RouteBuilderPointRoutingProxy(type: .start)
        let finish = RouteBuilderPointRoutingProxy(type: .finish)

        let synced = RouteBuilderPointRoutingProxy.syncAutoPathPoints(
            existing: [start, manual, staleAuto, finish],
            autoCoordinates: [(37.02, -122.0)]
        )

        XCTAssertEqual(synced.filter { $0.isAutoShape }.count, 1)
        XCTAssertEqual(synced.filter { $0.type == .path && !$0.isAutoGenerated }.count, 1)
        XCTAssertTrue(synced.contains(where: { $0.type == .start }))
        XCTAssertTrue(synced.contains(where: { $0.type == .finish }))
    }
}

private struct RouteBuilderPointRoutingProxy {
    enum PointType {
        case start
        case path
        case waypoint
        case stop
        case finish
    }

    let type: PointType
    var isAutoGenerated: Bool
    let id: UUID

    init(type: PointType, isAutoGenerated: Bool = false, id: UUID = UUID()) {
        self.type = type
        self.isAutoGenerated = isAutoGenerated
        self.id = id
    }

    var isAutoShape: Bool {
        type == .path && isAutoGenerated
    }

    func affectsRouting(activeDragPointID: UUID? = nil) -> Bool {
        switch type {
        case .waypoint, .stop:
            return false
        case .path:
            if isAutoGenerated {
                return id == activeDragPointID
            }
            return true
        case .start, .finish:
            return true
        }
    }

    static func moveAutoShape(originalID: UUID, newCoordinate: (Double, Double)) -> RouteBuilderPointRoutingProxy {
        RouteBuilderPointRoutingProxy(
            type: .path,
            isAutoGenerated: true,
            id: originalID
        )
    }

    static func moveUserPath(originalID: UUID, newCoordinate: (Double, Double)) -> RouteBuilderPointRoutingProxy {
        RouteBuilderPointRoutingProxy(
            type: .path,
            isAutoGenerated: false,
            id: originalID
        )
    }

    static func syncAutoPathPoints(
        existing: [RouteBuilderPointRoutingProxy],
        autoCoordinates: [(Double, Double)]
    ) -> [RouteBuilderPointRoutingProxy] {
        let preserved = existing.filter { !$0.isAutoShape }
        let autoPoints = autoCoordinates.map { _ in
            RouteBuilderPointRoutingProxy(type: .path, isAutoGenerated: true)
        }
        return preserved + autoPoints
    }
}
