import CoreLocation
import MapboxMaps
import MapKit
import SwiftUI

private struct RouteBuilderBottomBarMinYKey: PreferenceKey {
    static var defaultValue: CGFloat?

    static func reduce(value: inout CGFloat?, nextValue: () -> CGFloat?) {
        guard let next = nextValue() else { return }
        value = value.map { min($0, next) } ?? next
    }
}

private struct RouteBuilderFABPressStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .scaleEffect(configuration.isPressed ? 0.94 : 1)
            .opacity(configuration.isPressed ? 0.78 : 1)
            .animation(.easeOut(duration: 0.12), value: configuration.isPressed)
    }
}

private final class RouteBuilderMapRegionCache {
    var region: MKCoordinateRegion

    init(region: MKCoordinateRegion) {
        self.region = region
    }
}

private enum RouteBuilderPointType: String {
    case start
    case path
    case waypoint
    case stop
    case finish

    var title: String {
        switch self {
        case .start: return "Start"
        case .path: return "Path Marker"
        case .waypoint: return "Checkpoint"
        case .stop: return "Stop"
        case .finish: return "Finish"
        }
    }

    var systemImage: String {
        switch self {
        case .start: return "play.fill"
        case .path: return RouteMapMarkerAsset.pathInnerSymbolName
        case .waypoint: return "flag.fill"
        case .stop: return "octagon.fill"
        case .finish: return "flag.checkered"
        }
    }

    var color: Color {
        switch self {
        case .start: return RouteMapMarkerColors.startButton
        case .path: return .purple
        case .waypoint: return .blue
        case .stop: return .red
        case .finish: return .white
        }
    }

    var assetName: String {
        switch self {
        case .start: return "map-route-start"
        case .path: return "map-route-point"
        case .waypoint: return "map-route-checkpoint"
        case .stop: return "map-route-stop"
        case .finish: return "map-route-finish"
        }
    }
}

private struct RouteBuilderPoint: Identifiable {
    let id: UUID
    let coordinate: CLLocationCoordinate2D
    let type: RouteBuilderPointType
    /// Client-local only: `true` = auto shape handle (disposable, not saved, not routing input except during drag).
    var isAutoGenerated: Bool

    init(
        coordinate: CLLocationCoordinate2D,
        type: RouteBuilderPointType,
        isAutoGenerated: Bool = false,
        id: UUID = UUID()
    ) {
        self.id = id
        self.coordinate = coordinate
        self.type = type
        self.isAutoGenerated = isAutoGenerated
    }

    var isAutoShape: Bool {
        type == .path && isAutoGenerated
    }

    var isLockedIntentional: Bool {
        !isAutoShape
    }

    func affectsRouting(activeDragPointID: UUID? = nil) -> Bool {
        switch type {
        case .waypoint, .stop:
            return false
        case .path:
            if isAutoGenerated {
                return id == activeDragPointID
            }
            return true
        case .start, .finish:
            return true
        }
    }

    var displayTitle: String {
        isAutoShape ? "Route Bend" : type.title
    }
}

private struct RouteEditBaseline: Equatable {
    let name: String
    let pointSignatures: [String]
    let roadSignatures: [String]
    let distanceMeters: Double
    let travelSeconds: TimeInterval

    static func capture(
        name: String,
        points: [RouteBuilderPoint],
        roadCoordinates: [CLLocationCoordinate2D],
        distanceMeters: Double,
        travelSeconds: TimeInterval
    ) -> RouteEditBaseline {
        RouteEditBaseline(
            name: name.trimmingCharacters(in: .whitespacesAndNewlines),
            pointSignatures: points.filter { !$0.isAutoShape }.map(pointSignature),
            roadSignatures: roadCoordinates.map(coordinateSignature),
            distanceMeters: roundedDistance(distanceMeters),
            travelSeconds: travelSeconds.rounded()
        )
    }

    private static func pointSignature(_ point: RouteBuilderPoint) -> String {
        "\(point.type.rawValue)|\(coordinateSignature(point.coordinate))"
    }

    private static func coordinateSignature(_ coordinate: CLLocationCoordinate2D) -> String {
        String(format: "%.5f,%.5f", coordinate.latitude, coordinate.longitude)
    }

    private static func roundedDistance(_ value: Double) -> Double {
        (value * 10).rounded() / 10
    }

    func pathChanged(from roadCoordinates: [CLLocationCoordinate2D]) -> Bool {
        roadCoordinates.map(Self.coordinateSignature) != roadSignatures
    }
}

private struct RouteBuilderEditSnapshot {
    let intentionalPoints: [RouteBuilderPoint]
    let roadCoordinates: [CLLocationCoordinate2D]
    let distanceMeters: Double
    let travelSeconds: TimeInterval
    let didSnapToRoad: Bool
    let lastSnapTurnCoordinates: [CLLocationCoordinate2D]
    let selectedCheckpointDensity: CheckpointDensityTier

    static func capture(
        points: [RouteBuilderPoint],
        roadCoordinates: [CLLocationCoordinate2D],
        distanceMeters: Double,
        travelSeconds: TimeInterval,
        didSnapToRoad: Bool,
        lastSnapTurnCoordinates: [CLLocationCoordinate2D],
        selectedCheckpointDensity: CheckpointDensityTier
    ) -> RouteBuilderEditSnapshot {
        RouteBuilderEditSnapshot(
            intentionalPoints: points.filter { !$0.isAutoShape },
            roadCoordinates: roadCoordinates,
            distanceMeters: distanceMeters,
            travelSeconds: travelSeconds,
            didSnapToRoad: didSnapToRoad,
            lastSnapTurnCoordinates: lastSnapTurnCoordinates,
            selectedCheckpointDensity: selectedCheckpointDensity
        )
    }
}

private struct PendingCheckpointRegeneration: Equatable {
    let spacingMeters: Double?
    let densityTier: CheckpointDensityTier
}

struct RouteBuilderView: View {
    let initialCenter: CLLocationCoordinate2D
    let initialMapViewport: Viewport
    let onRouteSaved: ((SavedRouteDTO) -> Void)?

    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var appState: AppState
    @EnvironmentObject private var locationService: LocationService
    @StateObject private var perfDiagnostics = RouteBuilderPerfDiagnostics()
    @AppStorage(OttoDebugSettings.routeBuilderPerfOverlayKey) private var routeBuilderPerfOverlayEnabled = false
    @State private var editingRouteId: String? = nil
    @State private var programmaticMapViewport: Viewport?
    @State private var mapRegionCache: RouteBuilderMapRegionCache
    @State private var mapContainerSize: CGSize = .zero
    @State private var mapBottomSafeArea: CGFloat = 0
    @State private var measuredBottomBarMinY: CGFloat?
    @State private var routeName = "New Route"
    @State private var points: [RouteBuilderPoint] = []
    @State private var roadCoordinates: [CLLocationCoordinate2D] = []
    @State private var roadPolylineIndex: RoutePolylineIndex?
    @State private var mapMarkerLODTier: RouteBuilderMapMarkerLODTier = .street
    @State private var mapVisibleLatitudeDelta: Double = 0.008
    @State private var mapCameraDebounceTask: Task<Void, Never>?
    @State private var distanceMeters: Double = 0
    @State private var travelSeconds: TimeInterval = 0
    @State private var isSnapping = false
    @State private var didSnapToRoad = false
    @State private var isSaving = false
    @State private var isShowingRouteNamePrompt = false
    @State private var markerActionPointID: UUID?
    @State private var movingPointID: UUID?
    @State private var routePointPendingDeleteID: UUID?
    @State private var routeNameDraft = ""
    @State private var errorMessage: String?
    @State private var snapTask: Task<Void, Never>?
    @State private var polylineIndexTask: Task<Void, Never>?
    @State private var autoPathBootstrapTask: Task<Void, Never>?
    @State private var editBaseline: RouteEditBaseline?
    @State private var lastSnapTurnCoordinates: [CLLocationCoordinate2D] = []
    @State private var isManualMode = false
    @State private var isEditMode = false
    @State private var isRunningGuidedGeneration = false
    @State private var hasCompletedGuidedGeneration = false
    @State private var guidedBackToStartStep = false
    @State private var selectedCheckpointDensity: CheckpointDensityTier = .recommended
    @State private var activeCheckpointSpacingMeters: Double?
    @State private var pendingCheckpointRegeneration: PendingCheckpointRegeneration?
    @State private var editUndoStack: [RouteBuilderEditSnapshot] = []
    @State private var isShowingDiscardChangesAlert = false
    @State private var showRouteEducation = false
    @State private var showLocationPrimer = false
    @State private var didApplyUserLocationRecenter = false
    @State private var latestObservedCameraRegion: MKCoordinateRegion

    init(initialCenter: CLLocationCoordinate2D, onRouteSaved: ((SavedRouteDTO) -> Void)? = nil) {
        self.initialCenter = initialCenter
        self.onRouteSaved = onRouteSaved
        let region = MKCoordinateRegion(
            center: initialCenter,
            span: Self.newRouteMapSpan
        )
        self.initialMapViewport = OttoMapboxCamera.viewport(for: region)
        _mapRegionCache = State(initialValue: RouteBuilderMapRegionCache(region: region))
        _latestObservedCameraRegion = State(initialValue: region)
        _mapVisibleLatitudeDelta = State(initialValue: Self.markerLODLatitudeDelta(for: region))
        _mapMarkerLODTier = State(
            initialValue: RouteBuilderMapMarkerLODTier.from(
                latitudeDelta: Self.markerLODLatitudeDelta(for: region),
                regionalMinLatitudeDelta: Self.regionalDotMinLatitudeDelta,
                streetMaxLatitudeDelta: Self.secondaryMarkerFullSizeMaxLatitudeDelta
            )
        )
    }

    init(route: SavedRouteDTO, onRouteSaved: ((SavedRouteDTO) -> Void)? = nil) {
        let routePoints = route.points.compactMap { dto -> RouteBuilderPoint? in
            guard let coordinate = Self.coordinate(from: dto) else { return nil }
            return RouteBuilderPoint(
                coordinate: coordinate,
                type: RouteBuilderPointType(rawValue: dto.markerType ?? "") ?? .path
            )
        }
        let roadCoordinates = route.roadCoordinates.compactMap(Self.coordinate(from:))
        let displayCoordinates = roadCoordinates.count >= 2 ? roadCoordinates : routePoints.map(\.coordinate)
        let center = Self.centerCoordinate(for: displayCoordinates)
        let region = RouteMapGeometry.regionToFit(displayCoordinates, fallback: center)
        let hasStart = routePoints.contains { $0.type == .start }
        let hasFinish = routePoints.contains { $0.type == .finish }
        let opensInEditMode = hasStart && hasFinish
        let waypointCount = routePoints.filter { $0.type == .waypoint }.count
        let inferredCheckpointSpacing = Self.inferredCheckpointSpacingMeters(
            checkpointCount: waypointCount,
            roadCoordinates: roadCoordinates
        )
        self.initialCenter = center
        self.onRouteSaved = onRouteSaved
        self.initialMapViewport = OttoMapboxCamera.viewport(for: region)
        _editingRouteId = State(initialValue: route.id)
        _mapRegionCache = State(initialValue: RouteBuilderMapRegionCache(region: region))
        _latestObservedCameraRegion = State(initialValue: region)
        _mapVisibleLatitudeDelta = State(initialValue: Self.markerLODLatitudeDelta(for: region))
        _mapMarkerLODTier = State(
            initialValue: RouteBuilderMapMarkerLODTier.from(
                latitudeDelta: Self.markerLODLatitudeDelta(for: region),
                regionalMinLatitudeDelta: Self.regionalDotMinLatitudeDelta,
                streetMaxLatitudeDelta: Self.secondaryMarkerFullSizeMaxLatitudeDelta
            )
        )
        _roadPolylineIndex = State(initialValue: nil)
        _routeName = State(initialValue: route.name)
        _points = State(initialValue: routePoints)
        _roadCoordinates = State(initialValue: roadCoordinates)
        _distanceMeters = State(initialValue: route.distanceMeters)
        _travelSeconds = State(initialValue: route.etaSeconds)
        _didSnapToRoad = State(initialValue: roadCoordinates.count >= 2)
        _activeCheckpointSpacingMeters = State(initialValue: inferredCheckpointSpacing)
        _isManualMode = State(initialValue: opensInEditMode)
        _isEditMode = State(initialValue: opensInEditMode)
        _editBaseline = State(
            initialValue: RouteEditBaseline.capture(
                name: route.name,
                points: routePoints,
                roadCoordinates: roadCoordinates,
                distanceMeters: route.distanceMeters,
                travelSeconds: route.etaSeconds
            )
        )
    }

    var body: some View {
        routeBuilderStackWithLifecycle
            .alert("Route Builder", isPresented: errorAlertBinding) {
                Button("OK", role: .cancel) {}
            } message: {
                Text(errorMessage ?? "")
            }
            .alert("Name This Route", isPresented: $isShowingRouteNamePrompt) {
                TextField("Route name", text: $routeNameDraft)
                Button("Cancel", role: .cancel) {}
                Button("Save") {
                    attemptSave(named: routeNameDraft)
                }
            } message: {
                Text("Give this route a name before saving.")
            }
            .confirmationDialog("Marker Actions", isPresented: markerActionDialogBinding, titleVisibility: .visible) {
                markerActionDialogActions
            } message: {
                if let point = markerActionPoint {
                    Text(markerActionMessage(for: point))
                }
            }
            .alert("Delete Route Item?", isPresented: deleteRouteItemAlertBinding) {
                Button("Cancel", role: .cancel) { routePointPendingDeleteID = nil }
                Button("Delete", role: .destructive) { deletePendingRoutePoint() }
            } message: {
                Text("Removing this item will update the route path, route order, and distance/time estimates.")
            }
            .alert("Discard Changes?", isPresented: $isShowingDiscardChangesAlert) {
                Button("Cancel", role: .cancel) {}
                Button("Discard", role: .destructive) { dismiss() }
            } message: {
                Text("Closing now will lose your unsaved route edits.")
            }
    }

    private var routeBuilderStackWithLifecycle: some View {
        routeBuilderMainStack
            .onAppear(perform: handleRouteBuilderAppear)
            .onChange(of: mapMarkerLODTier) { _, _ in syncPerfDiagnosticsSnapshot() }
            .onChange(of: points.count) { _, _ in syncPerfDiagnosticsSnapshot() }
            .onChange(of: locationService.authorizationStatus) { _, _ in
                if editingRouteId == nil { bootstrapNewRouteMapCamera() }
            }
            .onChange(of: locationService.lastLocation) { _, _ in
                applyNewRouteUserLocationIfAvailable()
            }
            .onChange(of: locationService.mapLocationDisplayTick) { _, _ in
                applyNewRouteUserLocationIfAvailable()
            }
            .onChange(of: routeBuilderPerfOverlayEnabled) { _, enabled in
                guard appState.canAccessInternalDebugTools else { return }
                if enabled {
                    perfDiagnostics.activate()
                } else {
                    perfDiagnostics.deactivate()
                }
            }
            .onDisappear {
                snapTask?.cancel()
                mapCameraDebounceTask?.cancel()
                polylineIndexTask?.cancel()
                autoPathBootstrapTask?.cancel()
                #if DEBUG
                print("[RouteBuilder] editor dismissed — Mapbox map will unmount")
                OttoRouteBuilderDebugLog.editorOpenEnded()
                #endif
                appState.setRouteBuilderPresented(false)
                perfDiagnostics.deactivate()
            }
    }

    private var routeBuilderMainStack: some View {
        ZStack {
            routeBuilderMapLayer
            routeBuilderChromeOverlay
        }
        .background { routeBuilderLayoutProbe }
        .background(Color.black)
        .overlay { routeBuilderPrimerOverlay }
    }

    @ViewBuilder
    private var routeBuilderPrimerOverlay: some View {
        ZStack {
            if showRouteEducation {
                routeBuilderEducationDialog
                    .transition(.opacity.combined(with: .scale(scale: 0.96)))
            }
            if showLocationPrimer {
                routeBuilderLocationPrimerDialog
                    .transition(.opacity.combined(with: .scale(scale: 0.96)))
            }
        }
    }

    @ViewBuilder
    private var markerActionDialogActions: some View {
        if let point = markerActionPoint {
            Button("Move \(point.displayTitle)") {
                movingPointID = point.id
                markerActionPointID = nil
                appState.activeToast = AppToast(
                    text: "Move the map under the crosshair, then tap Move Here",
                    systemImage: "scope"
                )
            }
            if point.type != .start && point.type != .finish {
                Button("Delete \(point.displayTitle)", role: .destructive) {
                    routePointPendingDeleteID = point.id
                    markerActionPointID = nil
                }
            }
            Button("Cancel", role: .cancel) { markerActionPointID = nil }
        }
    }

    private var errorAlertBinding: Binding<Bool> {
        Binding(get: { errorMessage != nil }, set: { if !$0 { errorMessage = nil } })
    }

    private var markerActionDialogBinding: Binding<Bool> {
        Binding(get: { markerActionPointID != nil }, set: { if !$0 { markerActionPointID = nil } })
    }

    private var deleteRouteItemAlertBinding: Binding<Bool> {
        Binding(get: { routePointPendingDeleteID != nil }, set: { if !$0 { routePointPendingDeleteID = nil } })
    }

    private func handleRouteBuilderAppear() {
        #if DEBUG
        OttoRouteBuilderDebugLog.editorOpenBegan(routeId: editingRouteId, roadPointCount: roadCoordinates.count)
        #endif
        appState.setRouteBuilderPresented(true)
        if showsRouteBuilderPerfOverlay {
            perfDiagnostics.activate()
        }
        syncPerfDiagnosticsSnapshot()
        if !appState.hasRoutesAccess {
            dismiss()
            return
        }
        captureInitialEditBaselineIfNeeded()
        if editingRouteId == nil {
            bootstrapNewRouteMapCamera()
        }
        presentRouteBuilderPrimersIfNeeded()
        refreshRoadPolylineCache()
    }

    private var showsRouteBuilderPerfOverlay: Bool {
        routeBuilderPerfOverlayEnabled && appState.canAccessInternalDebugTools
    }

    private var routeBuilderMapLayer: some View {
        RouteBuilderMapHost(
            initialViewport: initialMapViewport,
            programmaticViewport: programmaticMapViewport,
            mapContent: currentMapContent,
            diagnostics: perfDiagnostics,
            onCameraChanged: scheduleObservedCameraChange,
            onGestureEnded: { scheduleCameraSettle(force: true) },
            onLongPress: handleMapLongPress,
            onMarkerLongPress: handleRouteMarkerLongPress(id:)
        )
        .equatable()
        .ignoresSafeArea()
        .zIndex(0)
    }

    private var routeBuilderChromeOverlay: some View {
        ZStack {
            topScrim
                .zIndex(1)

            placementCrosshair(
                mapSize: mapContainerSize,
                visibleMapBottom: routeBuilderVisibleMapBottom
            )
            .zIndex(2)

            if showsRouteBuilderPerfOverlay {
                RouteBuilderBodyRebuildProbe(diagnostics: perfDiagnostics)
                    .frame(width: 0, height: 0)
                    .allowsHitTesting(false)
            }

            if showsRouteBuilderPerfOverlay {
                routeBuilderPerfOverlayLayer
            }

            VStack(spacing: 0) {
                topBar
                    .padding(.horizontal, 16)
                    .padding(.top, 10)
                    .allowsHitTesting(true)
                Spacer()
                    .allowsHitTesting(false)
                routeBuilderBottomBar(bottomSafeArea: mapBottomSafeArea)
                    .allowsHitTesting(true)
            }
            .ignoresSafeArea(edges: .bottom)
            .zIndex(3)

            if uiState != .generatingRoute {
                routeBuilderRecenterFabOverlay
                    .zIndex(4)
            }

            if uiState == .generatingRoute {
                RouteBuilderGeneratingOverlay()
                    .zIndex(5)
            }
        }
        .coordinateSpace(name: Self.routeBuilderOverlayCoordinateSpace)
        .onPreferenceChange(RouteBuilderBottomBarMinYKey.self) { minY in
            guard let minY, minY.isFinite, minY > 0 else { return }
            measuredBottomBarMinY = minY
        }
    }

    private var routeBuilderRecenterFabOverlay: some View {
        ZStack(alignment: .topLeading) {
            routeBuilderRecenterButton
                .position(routeBuilderRecenterFabCenter)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }

    private var routeBuilderPerfOverlayLayer: some View {
        VStack {
            HStack {
                RouteBuilderPerfOverlay(diagnostics: perfDiagnostics)
                    .padding(.leading, 10)
                    .padding(.top, 56)
                Spacer(minLength: 0)
            }
            Spacer()
        }
        .allowsHitTesting(false)
        .zIndex(5)
    }

    private var routeBuilderLayoutProbe: some View {
        GeometryReader { proxy in
            Color.clear
                .task(id: "\(proxy.size.width)x\(proxy.size.height)-\(proxy.safeAreaInsets.bottom)") {
                    mapContainerSize = proxy.size
                    mapBottomSafeArea = proxy.safeAreaInsets.bottom
                }
        }
    }

    private var currentMapContent: RouteBuilderMapContent {
        let line = routeLineCoordinates
        let pathDots = nativePathDotsForDisplay()
        return RouteBuilderMapContent(
            lineFingerprint: RoutePolylineDisplayOptimizer.fingerprint(line),
            lineCoordinates: line,
            markers: mapMarkerSnapshots(),
            nativePathDotsFingerprint: pathDots.fingerprint,
            nativePathDots: pathDots,
            allowsInteraction: !isMapInteractionDisabled
        )
    }

    private func syncPerfDiagnosticsSnapshot() {
        perfDiagnostics.updateSnapshot(
            roadPoints: roadCoordinates.count,
            displayPoints: routeLineCoordinates.count,
            markers: points.count,
            visibleMarkers: mapPointsForDisplay().count,
            lodTier: mapMarkerLODTier,
            latitudeDelta: mapRegionCache.region.span.latitudeDelta,
            lightweightRendering: false
        )
    }

    private func mapMarkerSnapshots() -> [RouteBuilderMapMarkerSnapshot] {
        mapPointsForDisplay().map { entry in
            let point = entry.point
            let presentation = markerPresentation(for: point)
            return RouteBuilderMapMarkerSnapshot(
                id: point.id,
                coordinate: point.coordinate,
                markerType: point.type.rawValue,
                isAutoShape: point.isAutoShape,
                presentation: presentation,
                pinScale: markerPinScale(for: point),
                dotColor: point.type.color,
                accessibilityTitle: point.displayTitle,
                refreshID: routePointMarkerRefreshID(for: point),
                originalIndex: entry.originalIndex
            )
        }
    }

    private var usesWideRegionalLightweightRendering: Bool {
        mapMarkerLODTier == .regional
            && mapRegionCache.region.span.latitudeDelta > Self.regionalDotMinLatitudeDelta * 12
    }

    private func mapPointsForDisplay() -> [(point: RouteBuilderPoint, originalIndex: Int)] {
        let indexed = Array(points.enumerated()).map { (point: $0.element, originalIndex: $0.offset) }
        if usesWideRegionalLightweightRendering {
            return indexed.filter { $0.point.type == .start || $0.point.type == .finish }
        }
        return indexed
    }

    private func nativePathDotsForDisplay() -> RouteBuilderNativePathDotsState {
        // Path markers render as view annotations (same LOD / pin scale as checkpoint and stop).
        RouteBuilderNativePathDotsState(fingerprint: "empty", userDots: [], autoDots: [])
    }

    private func handleRouteMarkerLongPress(id: UUID) {
        guard let point = points.first(where: { $0.id == id }) else { return }
        handleRouteMarkerLongPress(point)
    }

    private var topBar: some View {
        ZStack {
            Text(editingRouteId == nil ? "New Rally Route" : routeName)
                .font(.headline.weight(.semibold))
                .foregroundStyle(.white)
                .lineLimit(1)
                .padding(.horizontal, showsEditSessionUndo ? 148 : 86)
                .frame(maxWidth: .infinity)
                #if DEBUG
                .onLongPressGesture(minimumDuration: 0.8) {
                    routeBuilderPerfOverlayEnabled.toggle()
                }
                #endif

            HStack {
                Button {
                    attemptClose()
                } label: {
                    OttoHeaderIconButtonLabel(systemImage: "xmark")
                }

                Spacer()

                if showsEditSessionUndo {
                    Button {
                        undoEditSessionChange()
                    } label: {
                        OttoHeaderTextButtonLabel(
                            title: RouteBuilderCopy.undo,
                            isEnabled: canUndoEditSession && !isSaving && !isSnapping
                        )
                    }
                    .disabled(!canUndoEditSession || isSaving || isSnapping)
                }

                Button {
                    beginSaveFlow()
                } label: {
                    OttoHeaderTextButtonLabel(title: "Save", isEnabled: saveIsActive)
                }
                .disabled(!saveIsActive || isSaving)
            }
        }
        .buttonStyle(.plain)
    }

    private var showsEditSessionUndo: Bool {
        uiState == .editRoute || uiState == .manualPlot
    }

    private var canUndoEditSession: Bool {
        !editUndoStack.isEmpty
    }

    private var isRouteEditSessionActive: Bool {
        showsEditSessionUndo
    }

    private var topScrim: some View {
        LinearGradient(
            colors: [.black.opacity(0.45), .black.opacity(0.16), .clear],
            startPoint: .top,
            endPoint: .bottom
        )
        .frame(height: 142)
        .frame(maxHeight: .infinity, alignment: .top)
        .ignoresSafeArea()
        .allowsHitTesting(false)
    }

    private func placementCrosshair(
        mapSize: CGSize,
        visibleMapBottom: CGFloat
    ) -> some View {
        let center = crosshairCenter(
            mapSize: mapSize,
            visibleMapBottom: visibleMapBottom
        )

        return RouteBuilderPlacementCrosshair()
            .position(center)
            .allowsHitTesting(false)
    }

    /// Map tab FAB gap above bottom chrome (`MapScreen.mapFabOverlayBottomPadding`).
    private static let mapFabOverlayBottomPadding: CGFloat = 18
    private static let mapFabHorizontalInset: CGFloat = 18
    private static let mapFabDiameter: CGFloat = 56
    private static let routeBuilderOverlayCoordinateSpace = "routeBuilderOverlay"

    private var routeBuilderVisibleMapBottom: CGFloat {
        if let measuredBottomBarMinY, measuredBottomBarMinY > 0 {
            return measuredBottomBarMinY
        }
        return max(0, mapContainerSize.height - estimatedBottomBarVisibleHeight(bottomSafeArea: mapBottomSafeArea))
    }

    private var routeBuilderRecenterFabCenter: CGPoint {
        let radius = Self.mapFabDiameter / 2
        return CGPoint(
            x: Self.mapFabHorizontalInset + radius,
            y: max(radius, routeBuilderVisibleMapBottom - Self.mapFabOverlayBottomPadding - radius)
        )
    }

    private func estimatedBottomBarVisibleHeight(bottomSafeArea: CGFloat) -> CGFloat {
        bottomBarContentHeight(for: uiState) + 12 + 14 + 18 + bottomSafeArea
    }

    private func bottomBarContentHeight(for state: RouteBuilderUIState) -> CGFloat {
        switch state {
        case .setStart: return 270
        case .setFinish: return 340
        case .generatingRoute: return 100
        case .routeReady: return 330
        case .manualPlot: return 400
        case .editRoute: return 420
        }
    }

    private var uiState: RouteBuilderUIState {
        RouteBuilderUIStateResolver.resolve(
            RouteBuilderUIStateResolver.Inputs(
                hasStart: hasStart,
                hasFinish: hasFinish,
                isRunningGuidedGeneration: isRunningGuidedGeneration,
                isSnapping: isSnapping,
                hasRoutePath: hasRoutePath,
                checkpointCount: checkpointCount,
                isManualMode: isManualMode,
                isEditMode: isEditMode,
                hasCompletedGuidedGeneration: hasCompletedGuidedGeneration,
                guidedBackToStartStep: guidedBackToStartStep
            )
        )
    }

    private var hasStart: Bool {
        points.contains { $0.type == .start }
    }

    private var hasFinish: Bool {
        points.contains { $0.type == .finish }
    }

    private var hasRoutePath: Bool {
        roadCoordinates.count >= 2 && didSnapToRoad
    }

    private var checkpointCount: Int {
        points.filter { $0.type == .waypoint }.count
    }

    private var isMapInteractionDisabled: Bool {
        uiState == .generatingRoute
    }

    private var currentTurnCount: Int {
        lastSnapTurnCoordinates.count
    }

    private func crosshairCenter(
        mapSize: CGSize,
        visibleMapBottom: CGFloat
    ) -> CGPoint {
        return CGPoint(x: mapSize.width / 2, y: visibleMapBottom / 2)
    }

    private var currentPlacementCoordinate: CLLocationCoordinate2D {
        guard mapContainerSize != .zero else {
            return placementCameraRegion.center
        }
        return Self.coordinateAtCrosshair(
            region: placementCameraRegion,
            mapSize: mapContainerSize,
            crosshairCenter: crosshairCenter(
                mapSize: mapContainerSize,
                visibleMapBottom: routeBuilderVisibleMapBottom
            )
        )
    }

    private var placementCameraRegion: MKCoordinateRegion {
        latestObservedCameraRegion
    }

    private static func coordinateAtCrosshair(
        region: MKCoordinateRegion,
        mapSize: CGSize,
        crosshairCenter: CGPoint
    ) -> CLLocationCoordinate2D {
        guard mapSize.width > 0, mapSize.height > 0 else { return region.center }

        let mapCenter = CGPoint(x: mapSize.width / 2, y: mapSize.height / 2)
        let offsetX = crosshairCenter.x - mapCenter.x
        let offsetY = crosshairCenter.y - mapCenter.y
        let latOffset = -offsetY * (region.span.latitudeDelta / mapSize.height)
        let lngOffset = offsetX * (region.span.longitudeDelta / mapSize.width)

        return CLLocationCoordinate2D(
            latitude: region.center.latitude + latOffset,
            longitude: region.center.longitude + lngOffset
        )
    }

    private func routeBuilderBottomBar(bottomSafeArea: CGFloat) -> some View {
        RouteBuilderBottomSheet(
            uiState: uiState,
            checkpointCount: checkpointCount,
            isSaving: isSaving,
            isInteractionDisabled: isMapInteractionDisabled,
            canDecreaseCheckpointDensity: canStepCheckpointDensity(direction: -1),
            canIncreaseCheckpointDensity: canStepCheckpointDensity(direction: 1),
            isMovingPoint: movingPointID != nil,
            onSetStart: { placeStartFromGuidedFlow() },
            onSetFinish: { placeFinishForGuidedFlow() },
            onBuildManually: { enterManualMode() },
            onBackFromSetFinish: { goBackFromSetFinish() },
            onBackFromRouteReady: { goBackFromRouteReady() },
            onLooksGood: { enterEditModeFromRouteReady() },
            onFewerCheckpoints: { stepCheckpointDensity(direction: -1) },
            onMoreCheckpoints: { stepCheckpointDensity(direction: 1) },
            onShapeRoute: { placePoint(.path) },
            onAddCheckpoint: { placePoint(.waypoint) },
            onAddStop: { placePoint(.stop) },
            onMoveHere: { moveSelectedPointToCenterPin() },
            onCancelMove: { cancelMovePoint() }
        )
        .padding(.horizontal, 16)
        .padding(.top, 12)
        .padding(.bottom, 14 + bottomSafeArea)
        .frame(maxWidth: .infinity, alignment: .topLeading)
        .background(routeOrganizerBackground)
        .clipShape(UnevenRoundedRectangle(topLeadingRadius: 28, bottomLeadingRadius: 0, bottomTrailingRadius: 0, topTrailingRadius: 28, style: .continuous))
        .overlay(
            UnevenRoundedRectangle(topLeadingRadius: 28, bottomLeadingRadius: 0, bottomTrailingRadius: 0, topTrailingRadius: 28, style: .continuous)
                .stroke(Color.white.opacity(0.11), lineWidth: 1)
        )
        .shadow(color: .black.opacity(0.38), radius: 24, y: -10)
        .background {
            GeometryReader { proxy in
                Color.clear.preference(
                    key: RouteBuilderBottomBarMinYKey.self,
                    value: proxy.frame(in: .named(Self.routeBuilderOverlayCoordinateSpace)).minY
                )
            }
        }
        .zIndex(10)
        .ignoresSafeArea(edges: .bottom)
    }

    private func resetEditUndoSession() {
        editUndoStack.removeAll()
    }

    private func recordEditUndoSnapshotBeforeChange() {
        guard isRouteEditSessionActive, !isSaving else { return }
        editUndoStack.append(
            RouteBuilderEditSnapshot.capture(
                points: points,
                roadCoordinates: roadCoordinates,
                distanceMeters: distanceMeters,
                travelSeconds: travelSeconds,
                didSnapToRoad: didSnapToRoad,
                lastSnapTurnCoordinates: lastSnapTurnCoordinates,
                selectedCheckpointDensity: selectedCheckpointDensity
            )
        )
        if editUndoStack.count > 50 {
            editUndoStack.removeFirst(editUndoStack.count - 50)
        }
    }

    private func undoEditSessionChange() {
        guard let snapshot = editUndoStack.popLast() else { return }
        RouteBuilderHaptics.buttonTap()
        snapTask?.cancel()
        isSnapping = false
        isRunningGuidedGeneration = false
        movingPointID = nil
        markerActionPointID = nil
        routePointPendingDeleteID = nil
        applyEditSnapshot(snapshot)
    }

    private func applyEditSnapshot(_ snapshot: RouteBuilderEditSnapshot) {
        points = snapshot.intentionalPoints
        roadCoordinates = snapshot.roadCoordinates
        distanceMeters = snapshot.distanceMeters
        travelSeconds = snapshot.travelSeconds
        didSnapToRoad = snapshot.didSnapToRoad
        lastSnapTurnCoordinates = snapshot.lastSnapTurnCoordinates
        selectedCheckpointDensity = snapshot.selectedCheckpointDensity

        if snapshot.didSnapToRoad, snapshot.roadCoordinates.count >= 2 {
            roadPolylineIndex = RoutePolylineIndex(lineCoordinates: snapshot.roadCoordinates)
            syncAutoPathPoints(turnCoordinates: snapshot.lastSnapTurnCoordinates)
            refreshRoadPolylineCache()
        } else if routingCoordinates().count >= 2 {
            rebuildRoadPath()
        } else {
            refreshRoadPolylineCache()
        }
    }

    private func enterManualMode() {
        resetEditUndoSession()
        isManualMode = true
        isEditMode = false
        hasCompletedGuidedGeneration = false
        isRunningGuidedGeneration = false
    }

    private func enterEditModeFromRouteReady() {
        resetEditUndoSession()
        withAnimation(.easeInOut(duration: 0.18)) {
            isEditMode = true
            isManualMode = true
        }
    }

    private func placeStartFromGuidedFlow() {
        guidedBackToStartStep = false
        placePoint(.start)
    }

    private func goBackFromSetFinish() {
        guidedBackToStartStep = true
        points.removeAll { $0.type == .finish }
        points.removeAll { $0.isAutoShape }
        roadCoordinates = []
        didSnapToRoad = false
        distanceMeters = 0
        travelSeconds = 0
        lastSnapTurnCoordinates = []
        isRunningGuidedGeneration = false
        hasCompletedGuidedGeneration = false
    }

    private func goBackFromRouteReady() {
        resetEditUndoSession()
        activeCheckpointSpacingMeters = nil
        hasCompletedGuidedGeneration = false
        guidedBackToStartStep = false
        selectedCheckpointDensity = .recommended
        points.removeAll { $0.type == .waypoint }
        points.removeAll { $0.isAutoShape }
        points.removeAll { $0.type == .finish }
        roadCoordinates = []
        didSnapToRoad = false
        distanceMeters = 0
        travelSeconds = 0
        lastSnapTurnCoordinates = []
        isRunningGuidedGeneration = false
        pendingCheckpointRegeneration = nil
    }

    private func placeFinishForGuidedFlow() {
        placePoint(.finish, triggerGuidedGeneration: !isManualMode && !isEditMode)
    }

    private func cancelMovePoint() {
        movingPointID = nil
    }

    private func startGuidedRouteGeneration() {
        isRunningGuidedGeneration = true
        rebuildRoadPath()
    }

    private func handleGuidedGenerationComplete() {
        isRunningGuidedGeneration = false
        guard didSnapToRoad else {
            isManualMode = true
            errorMessage = "Couldn’t build a route along roads. Try building manually or adjust your start and finish."
            return
        }
        guard distanceMeters >= Self.minimumRouteDriveDistanceMeters else {
            isManualMode = true
            errorMessage = "Route drive distance must be at least 1,000 feet. Adjust your start or finish."
            return
        }
        applyCheckpointsForDensity(.recommended)
        hasCompletedGuidedGeneration = true
        selectedCheckpointDensity = .recommended
    }

    private func stepCheckpointDensity(direction: Int) {
        let options = sortedCheckpointSpacingOptions()
        guard options.count > 1 else { return }

        let currentIndex = currentCheckpointSpacingIndex(in: options)
        let nextIndex = currentIndex + direction
        guard options.indices.contains(nextIndex) else { return }

        let next = options[nextIndex]
        guard next.spacingMeters != options[currentIndex].spacingMeters else { return }
        replaceAutoCheckpoints(spacingMeters: next.spacingMeters)
        syncSelectedCheckpointDensity(for: next)
        RouteBuilderHaptics.buttonTap()
    }

    private func sortedCheckpointSpacingOptions() -> [RouteAutoCheckpointGenerator.IntervalOption] {
        RouteAutoCheckpointGenerator.viableIntervals(roadCoordinates: roadCoordinates)
            .sorted { $0.spacingMeters > $1.spacingMeters }
    }

    private func currentCheckpointSpacingIndex(
        in options: [RouteAutoCheckpointGenerator.IntervalOption]
    ) -> Int {
        if let activeCheckpointSpacingMeters,
           let index = options.firstIndex(where: { $0.spacingMeters == activeCheckpointSpacingMeters }) {
            return index
        }

        guard !options.isEmpty else { return 0 }
        let currentCount = checkpointCount
        return options.enumerated().min(by: { lhs, rhs in
            let lhsDelta = abs(lhs.element.checkpointCount - currentCount)
            let rhsDelta = abs(rhs.element.checkpointCount - currentCount)
            if lhsDelta != rhsDelta { return lhsDelta < rhsDelta }
            return lhs.offset < rhs.offset
        })?.offset ?? 0
    }

    private func canStepCheckpointDensity(direction: Int) -> Bool {
        let options = sortedCheckpointSpacingOptions()
        guard options.count > 1 else { return false }
        let nextIndex = currentCheckpointSpacingIndex(in: options) + direction
        guard options.indices.contains(nextIndex) else { return false }
        return options[nextIndex].spacingMeters != options[currentCheckpointSpacingIndex(in: options)].spacingMeters
    }

    private func syncSelectedCheckpointDensity(for interval: RouteAutoCheckpointGenerator.IntervalOption) {
        if let option = RouteAutoCheckpointGenerator.densityOption(
            for: .recommended,
            roadCoordinates: roadCoordinates,
            turnCount: currentTurnCount
        ), option.spacingMeters == interval.spacingMeters {
            selectedCheckpointDensity = .recommended
            return
        }

        let options = RouteAutoCheckpointGenerator.densityOptions(
            roadCoordinates: roadCoordinates,
            turnCount: currentTurnCount
        )
        selectedCheckpointDensity = options.first(where: { $0.spacingMeters == interval.spacingMeters })?.tier ?? .recommended
    }

    private func applyCheckpointsForDensity(_ tier: CheckpointDensityTier, recordUndo: Bool = true) {
        if let option = RouteAutoCheckpointGenerator.densityOption(
            for: tier,
            roadCoordinates: roadCoordinates,
            turnCount: currentTurnCount
        ) {
            replaceAutoCheckpoints(spacingMeters: option.spacingMeters, recordUndo: recordUndo)
            selectedCheckpointDensity = option.tier
            return
        }

        guard tier == .recommended,
              let recommended = RouteAutoCheckpointGenerator.recommendedDefaultInterval(
                roadCoordinates: roadCoordinates,
                turnCount: currentTurnCount
              ) else {
            return
        }

        replaceAutoCheckpoints(spacingMeters: recommended.spacingMeters, recordUndo: recordUndo)
        selectedCheckpointDensity = .recommended
    }

    private func replaceAutoCheckpoints(spacingMeters: Double, recordUndo: Bool = true) {
        guard roadCoordinates.count >= 2 else { return }

        let generated = RouteAutoCheckpointGenerator.generate(
            roadCoordinates: roadCoordinates,
            spacingMeters: spacingMeters
        )
        guard !generated.isEmpty else { return }

        if recordUndo, isRouteEditSessionActive {
            recordEditUndoSnapshotBeforeChange()
        }

        let newWaypoints = generated.map { RouteBuilderPoint(coordinate: $0, type: .waypoint) }
        withAnimation(.easeInOut(duration: 0.22)) {
            points = orderRoutePoints(points.filter { $0.type != .waypoint } + newWaypoints)
        }
        activeCheckpointSpacingMeters = spacingMeters
    }

    /// Strips stale checkpoint markers before endpoint moves; regeneration runs after the route re-snaps.
    private func prepareCheckpointRegenerationAfterEndpointChange() {
        let hadCheckpoints = checkpointCount > 0
        guard hadCheckpoints || activeCheckpointSpacingMeters != nil || hasCompletedGuidedGeneration else { return }

        var spacing = activeCheckpointSpacingMeters
        if spacing == nil, hadCheckpoints {
            spacing = inferredCheckpointSpacingMeters(
                checkpointCount: checkpointCount,
                roadCoordinates: roadCoordinates
            )
        }

        pendingCheckpointRegeneration = PendingCheckpointRegeneration(
            spacingMeters: spacing,
            densityTier: selectedCheckpointDensity
        )
        points.removeAll { $0.type == .waypoint }
    }

    private func applyPendingCheckpointRegenerationIfNeeded() {
        guard let pending = pendingCheckpointRegeneration else { return }
        pendingCheckpointRegeneration = nil
        guard roadCoordinates.count >= 2, didSnapToRoad else { return }

        if let spacing = pending.spacingMeters {
            regenerateCheckpointsPreservingSpacing(spacing, recordUndo: false)
            return
        }

        applyCheckpointsForDensity(pending.densityTier, recordUndo: false)
    }

    private func regenerateCheckpointsPreservingSpacing(_ spacing: Double, recordUndo: Bool) {
        guard roadCoordinates.count >= 2 else { return }
        let intervals = RouteAutoCheckpointGenerator.viableIntervals(roadCoordinates: roadCoordinates)
        guard !intervals.isEmpty else {
            activeCheckpointSpacingMeters = nil
            return
        }

        let spacingToUse: Double
        if intervals.contains(where: { $0.spacingMeters == spacing }) {
            spacingToUse = spacing
        } else if let nearest = intervals.min(by: {
            abs($0.spacingMeters - spacing) < abs($1.spacingMeters - spacing)
        }) {
            spacingToUse = nearest.spacingMeters
        } else {
            activeCheckpointSpacingMeters = nil
            return
        }

        replaceAutoCheckpoints(spacingMeters: spacingToUse, recordUndo: recordUndo)
        if let interval = intervals.first(where: { $0.spacingMeters == spacingToUse }) {
            syncSelectedCheckpointDensity(for: interval)
        }
    }

    private static func inferredCheckpointSpacingMeters(
        checkpointCount: Int,
        roadCoordinates: [CLLocationCoordinate2D]
    ) -> Double? {
        guard checkpointCount > 0, roadCoordinates.count >= 2 else { return nil }
        let intervals = RouteAutoCheckpointGenerator.viableIntervals(roadCoordinates: roadCoordinates)
        return intervals.min(by: {
            abs($0.checkpointCount - checkpointCount) < abs($1.checkpointCount - checkpointCount)
        })?.spacingMeters
    }

    private func inferredCheckpointSpacingMeters(
        checkpointCount: Int,
        roadCoordinates: [CLLocationCoordinate2D]
    ) -> Double? {
        Self.inferredCheckpointSpacingMeters(
            checkpointCount: checkpointCount,
            roadCoordinates: roadCoordinates
        )
    }

    private var routeOrganizerBackground: some View {
        ZStack {
            UnevenRoundedRectangle(topLeadingRadius: 28, bottomLeadingRadius: 0, bottomTrailingRadius: 0, topTrailingRadius: 28, style: .continuous)
                .fill(Color.black)
            UnevenRoundedRectangle(topLeadingRadius: 28, bottomLeadingRadius: 0, bottomTrailingRadius: 0, topTrailingRadius: 28, style: .continuous)
                .fill(
                    LinearGradient(
                        colors: [Color.white.opacity(0.055), Color.purple.opacity(0.045), Color.clear],
                        startPoint: .top,
                        endPoint: .bottom
                    )
                )
        }
    }

    private var canSave: Bool {
        hasStart
            && hasFinish
            && hasRoutePath
            && distanceMeters >= Self.minimumRouteDriveDistanceMeters
            && !isSnapping
            && !isRunningGuidedGeneration
    }

    private var hasUnsavedChanges: Bool {
        guard let baseline = editBaseline else { return true }
        let current = RouteEditBaseline.capture(
            name: routeName,
            points: points,
            roadCoordinates: roadCoordinates,
            distanceMeters: distanceMeters,
            travelSeconds: travelSeconds
        )
        return current != baseline
    }

    private var saveIsActive: Bool {
        guard canSave else { return false }
        if editingRouteId == nil { return true }
        return hasUnsavedChanges
    }

    private var routeLineCoordinates: [CLLocationCoordinate2D] {
        if roadCoordinates.count >= 2 {
            return roadCoordinates
        }
        return points.map(\.coordinate)
    }

    private func scheduleObservedCameraChange(_ region: MKCoordinateRegion) {
        latestObservedCameraRegion = region
        guard shouldApplyCameraChange(region) else { return }
        perfDiagnostics.recordCameraEvent()
        mapRegionCache.region = region
        OttoRouteBuilderDebugLog.cameraChangedWhileGesturing()
    }

    private func shouldApplyCameraChange(_ region: MKCoordinateRegion) -> Bool {
        let currentCenter = CLLocation(
            latitude: mapRegionCache.region.center.latitude,
            longitude: mapRegionCache.region.center.longitude
        )
        let nextCenter = CLLocation(latitude: region.center.latitude, longitude: region.center.longitude)
        let centerMovedMeters = currentCenter.distance(from: nextCenter)
        let spanChanged = abs(mapVisibleLatitudeDelta - region.span.latitudeDelta) > 0.00005
        return centerMovedMeters > 2 || spanChanged
    }

    private func scheduleCameraSettle(force: Bool) {
        mapCameraDebounceTask?.cancel()
        mapCameraDebounceTask = Task { @MainActor in
            try? await Task.sleep(nanoseconds: force ? 0 : 200_000_000)
            guard !Task.isCancelled else { return }
            applyCameraSettle(from: mapRegionCache.region)
        }
    }

    private func applyCameraSettle(from region: MKCoordinateRegion) {
        let latitudeDelta = Self.markerLODLatitudeDelta(for: region)
        let settledTier = RouteBuilderMapMarkerLODTier.from(
            latitudeDelta: latitudeDelta,
            regionalMinLatitudeDelta: Self.regionalDotMinLatitudeDelta,
            streetMaxLatitudeDelta: Self.secondaryMarkerFullSizeMaxLatitudeDelta
        )

        if settledTier != mapMarkerLODTier {
            mapMarkerLODTier = settledTier
            perfDiagnostics.recordStateWrite("mapMarkerLODTier (settle)")
            OttoRouteBuilderDebugLog.lodTierSettled(String(describing: settledTier), latitudeDelta: latitudeDelta)
        }

        mapVisibleLatitudeDelta = latitudeDelta
        perfDiagnostics.recordStateWrite("mapVisibleLatitudeDelta (settle)")
        syncPerfDiagnosticsSnapshot()
        scheduleAutoPathBootstrapIfZoomedIn()
    }

    private func scheduleRoadPolylineIndexBuild() {
        polylineIndexTask?.cancel()
        let line = routeLineCoordinates
        guard line.count >= 2 else {
            roadPolylineIndex = nil
            return
        }
        polylineIndexTask = Task {
            let index = RoutePolylineIndex(lineCoordinates: line)
            guard !Task.isCancelled else { return }
            await MainActor.run {
                roadPolylineIndex = index
                #if DEBUG
                OttoRouteBuilderDebugLog.polylineIndexBuilt(pointCount: line.count)
                #endif
            }
        }
    }

    private func scheduleAutoPathBootstrapIfZoomedIn() {
        guard mapMarkerLODTier != .regional else { return }
        guard !points.contains(where: { $0.isAutoShape }) else { return }
        autoPathBootstrapTask?.cancel()
        autoPathBootstrapTask = Task { @MainActor in
            try? await Task.sleep(nanoseconds: 350_000_000)
            guard !Task.isCancelled else { return }
            bootstrapAutoPathPointsIfNeeded()
        }
    }

    private func refreshRoadPolylineCache() {
        scheduleRoadPolylineIndexBuild()
    }

    private func projectOntoRouteLine(_ coordinate: CLLocationCoordinate2D) -> RoutePolylineProjection? {
        if let roadPolylineIndex {
            return roadPolylineIndex.projectOntoPolyline(coordinate)
        }
        return RouteMapGeometry.projectOntoPolyline(coordinate, onto: routeLineCoordinates)
    }

    private func projectOntoRouteLine(
        _ coordinate: CLLocationCoordinate2D,
        preferredArcLength: Double?,
        searchWindowMeters: CLLocationDistance = 350
    ) -> RoutePolylineProjection? {
        if let roadPolylineIndex {
            return roadPolylineIndex.projectOntoPolyline(
                coordinate,
                preferredArcLength: preferredArcLength,
                searchWindowMeters: searchWindowMeters
            )
        }
        return RouteMapGeometry.projectOntoPolyline(
            coordinate,
            onto: routeLineCoordinates,
            preferredArcLength: preferredArcLength,
            searchWindowMeters: searchWindowMeters
        )
    }

    private func routingCoordinates(activeDragPointID: UUID? = nil) -> [CLLocationCoordinate2D] {
        let candidates = points.filter { $0.affectsRouting(activeDragPointID: activeDragPointID) }
        return orderRoutePoints(candidates).map(\.coordinate)
    }

    private var distanceSummary: String {
        guard distanceMeters > 0 else { return "\(points.count) points" }
        let miles = distanceMeters / 1609.344
        let minutes = max(1, Int((travelSeconds / 60).rounded()))
        return String(format: "%.1f mi • %d min", miles, minutes)
    }

    private var markerActionPoint: RouteBuilderPoint? {
        guard let markerActionPointID else { return nil }
        return points.first { $0.id == markerActionPointID }
    }

    private enum RouteBuilderMarkerPresentation {
        case endpointPin
        case dot
        case pin
    }

    private func markerPresentation(for point: RouteBuilderPoint) -> RouteBuilderMapMarkerPresentation {
        switch routeBuilderMarkerPresentation(for: point) {
        case .endpointPin: return .endpointPin
        case .dot: return .dot
        case .pin: return .pin
        }
    }

    private func routeBuilderMarkerPresentation(for point: RouteBuilderPoint) -> RouteBuilderMarkerPresentation {
        if point.type == .start || point.type == .finish {
            return .endpointPin
        }
        if mapMarkerLODTier == .regional {
            return .dot
        }
        return .pin
    }

    private func markerPinScale(for point: RouteBuilderPoint) -> CGFloat {
        if point.type == .start || point.type == .finish {
            return 1
        }
        if usesZoomAwareSubtleScale(for: point) {
            return zoomAwareMarkerPinScale()
        }
        return 1
    }

    private func zoomAwareMarkerPinScale() -> CGFloat {
        let span = mapVisibleLatitudeDelta
        let far = Self.regionalDotMinLatitudeDelta
        let close = Self.secondaryMarkerFullSizeMaxLatitudeDelta
        if span <= close { return 1 }
        let range = far - close
        guard range > 0 else { return Self.routeBuilderSubtleMarkerScale }
        let t = min(1, max(0, (far - span) / range))
        return Self.routeBuilderSubtleMarkerScale + t * (1 - Self.routeBuilderSubtleMarkerScale)
    }

    private func usesZoomAwareSubtleScale(for point: RouteBuilderPoint) -> Bool {
        point.type == .path || point.type == .waypoint || point.type == .stop
    }

    /// Beyond ~5 mi visible — checkpoint, stop, and path markers render as colored dots.
    private var isRegionalDotZoom: Bool {
        mapMarkerLODTier == .regional
    }

    private func routePointMarkerRefreshID(for point: RouteBuilderPoint) -> String {
        switch markerPresentation(for: point) {
        case .endpointPin:
            return point.id.uuidString
        case .dot:
            return "\(point.id)-dot-\(mapMarkerLODTier)"
        case .pin:
            return "\(point.id)-pin-\(mapMarkerLODTier)-\(pinScaleRefreshBucket(for: point))"
        }
    }

    private func pinScaleRefreshBucket(for point: RouteBuilderPoint) -> Int {
        guard usesZoomAwareSubtleScale(for: point) else { return 0 }
        return Int((zoomAwareMarkerPinScale() * 10).rounded())
    }

    private func markerActionMessage(for point: RouteBuilderPoint) -> String {
        if point.type == .start || point.type == .finish {
            return "Move this endpoint while keeping its role."
        }
        if point.isAutoShape {
            return "Drag this bend to reshape the route."
        }
        return "Move or delete this point, then the route will rebuild."
    }

    private func handleRouteMarkerLongPress(_ point: RouteBuilderPoint) {
        guard uiState != .generatingRoute else { return }
        markerActionPointID = point.id
    }

    private func handleMapLongPress(at _: CLLocationCoordinate2D) {}

    private func moveSelectedPointToCenterPin() {
        guard let movingPointID,
              let index = points.firstIndex(where: { $0.id == movingPointID }) else {
            return
        }
        if isRouteEditSessionActive {
            recordEditUndoSnapshotBeforeChange()
        }
        let original = points[index]
        let raw = currentPlacementCoordinate
        let newCoordinate = snappedCoordinateForPlacement(type: original.type, raw: raw)
        applyMovedPoint(original: original, index: index, newCoordinate: newCoordinate)
    }

    private func applyMovedPoint(
        original: RouteBuilderPoint,
        index: Int,
        newCoordinate: CLLocationCoordinate2D
    ) {
        let activeDragPointID: UUID?

        if original.isAutoShape {
            let lockedPoints = points.filter { !$0.isAutoShape }
            let draggedShape = RouteBuilderPoint(
                coordinate: newCoordinate,
                type: .path,
                isAutoGenerated: true,
                id: original.id
            )
            points = lockedPoints + [draggedShape]
            if let projection = projectOntoRouteLine(newCoordinate) {
                points = orderRoutePoints(points, projectedPositions: [draggedShape.id: projection.arcLengthMeters])
            } else {
                points = orderRoutePoints(points)
            }
            activeDragPointID = draggedShape.id
        } else {
            let moved = RouteBuilderPoint(
                coordinate: newCoordinate,
                type: original.type,
                isAutoGenerated: original.isAutoGenerated,
                id: original.id
            )
            points[index] = moved
            if let projection = projectOntoRouteLine(newCoordinate) {
                points = orderRoutePoints(points, projectedPositions: [moved.id: projection.arcLengthMeters])
            } else {
                points = orderRoutePoints(points)
            }
            activeDragPointID = nil
        }

        self.movingPointID = nil
        if original.type == .start || original.type == .finish {
            prepareCheckpointRegenerationAfterEndpointChange()
        }
        if shouldRebuildRouteAfterPointMutation(for: original.type) {
            rebuildRoadPath(activeDragPointID: activeDragPointID)
        } else if original.type == .waypoint || original.type == .stop {
            points = orderRoutePoints(points)
        }
    }

    private func canDeleteRoutePoint(_ point: RouteBuilderPoint) -> Bool {
        point.type != .start && point.type != .finish
    }

    private func deletePendingRoutePoint() {
        guard let routePointPendingDeleteID,
              let point = points.first(where: { $0.id == routePointPendingDeleteID }),
              canDeleteRoutePoint(point) else {
            self.routePointPendingDeleteID = nil
            return
        }

        if isRouteEditSessionActive {
            recordEditUndoSnapshotBeforeChange()
        }

        points.removeAll { $0.id == routePointPendingDeleteID }
        if movingPointID == routePointPendingDeleteID {
            movingPointID = nil
        }
        markerActionPointID = nil
        self.routePointPendingDeleteID = nil
        if shouldRebuildRouteAfterPointMutation(for: point.type) {
            rebuildRoadPath()
        }
    }

    private func snappedCoordinateForPlacement(type: RouteBuilderPointType, raw: CLLocationCoordinate2D) -> CLLocationCoordinate2D {
        guard routeLineCoordinates.count >= 2 else { return raw }
        switch type {
        case .waypoint, .stop:
            return projectOntoRouteLine(raw)?.coordinate ?? raw
        case .start, .finish, .path:
            return raw
        }
    }

    private func placePoint(_ type: RouteBuilderPointType, triggerGuidedGeneration: Bool = false) {
        if isRouteEditSessionActive {
            recordEditUndoSnapshotBeforeChange()
        }
        let raw = currentPlacementCoordinate
        let coordinate = snappedCoordinateForPlacement(type: type, raw: raw)
        applyPlacedPoint(type, coordinate: coordinate, triggerGuidedGeneration: triggerGuidedGeneration)
    }

    private func applyPlacedPoint(
        _ type: RouteBuilderPointType,
        coordinate: CLLocationCoordinate2D,
        triggerGuidedGeneration: Bool
    ) {
        let point = RouteBuilderPoint(coordinate: coordinate, type: type)
        switch type {
        case .start:
            if let index = points.firstIndex(where: { $0.type == .start }) {
                points[index] = point
            } else {
                points.insert(point, at: 0)
            }
        case .finish:
            if let index = points.firstIndex(where: { $0.type == .finish }) {
                points[index] = point
            } else {
                points.append(point)
            }
        case .path, .waypoint, .stop:
            if routeLineCoordinates.count >= 2 {
                let projection = projectOntoRouteLine(point.coordinate)
                var nextPoints = points + [point]
                nextPoints = orderRoutePoints(
                    nextPoints,
                    projectedPositions: projection.map { [point.id: $0.arcLengthMeters] } ?? [:]
                )
                points = nextPoints
            } else if let finishIndex = points.firstIndex(where: { $0.type == .finish }) {
                points.insert(point, at: finishIndex)
            } else {
                points.append(point)
            }
        }
        if type == .start || type == .finish {
            prepareCheckpointRegenerationAfterEndpointChange()
        }
        if triggerGuidedGeneration {
            startGuidedRouteGeneration()
        } else if shouldRebuildRouteAfterPointMutation(for: type) {
            rebuildRoadPath()
        }
    }

    private func shouldRebuildRouteAfterPointMutation(for type: RouteBuilderPointType) -> Bool {
        switch type {
        case .start, .finish, .path:
            return true
        case .waypoint, .stop:
            return false
        }
    }

    private func orderRoutePoints(
        _ candidatePoints: [RouteBuilderPoint],
        projectedPositions: [UUID: Double] = [:]
    ) -> [RouteBuilderPoint] {
        guard candidatePoints.count >= 2, routeLineCoordinates.count >= 2 else {
            return candidatePoints
        }
        let start = candidatePoints.first { $0.type == .start }
        let finish = candidatePoints.first { $0.type == .finish }
        let interior = candidatePoints.filter { $0.type != .start && $0.type != .finish }
        let sortedInterior = interior.enumerated().sorted { lhs, rhs in
            let lhsPosition = projectedPositions[lhs.element.id]
                ?? projectOntoRouteLine(lhs.element.coordinate)?.arcLengthMeters
                ?? Double(lhs.offset)
            let rhsPosition = projectedPositions[rhs.element.id]
                ?? projectOntoRouteLine(rhs.element.coordinate)?.arcLengthMeters
                ?? Double(rhs.offset)
            if lhsPosition == rhsPosition {
                return lhs.offset < rhs.offset
            }
            return lhsPosition < rhsPosition
        }.map(\.element)
        return [start].compactMap { $0 } + sortedInterior + [finish].compactMap { $0 }
    }

    private func rebuildRoadPath(activeDragPointID: UUID? = nil) {
        snapTask?.cancel()
        let routingInput = routingCoordinates(activeDragPointID: activeDragPointID)
        guard routingInput.count >= 2 else {
            roadCoordinates = routingInput
            distanceMeters = 0
            travelSeconds = 0
            isSnapping = false
            didSnapToRoad = false
            lastSnapTurnCoordinates = []
            refreshRoadPolylineCache()
            if isRunningGuidedGeneration {
                isRunningGuidedGeneration = false
                isManualMode = true
            }
            pendingCheckpointRegeneration = nil
            return
        }
        roadCoordinates = []
        didSnapToRoad = false
        isSnapping = true
        snapTask = Task {
            let result = await RouteRoadSnapper.buildRoute(for: routingInput)
            guard !Task.isCancelled else { return }
            await MainActor.run {
                roadCoordinates = result.coordinates
                distanceMeters = result.distanceMeters
                travelSeconds = result.travelTimeSeconds
                didSnapToRoad = result.didSnapToRoad
                isSnapping = false
                lastSnapTurnCoordinates = result.turnManeuverCoordinates
                syncAutoPathPoints(turnCoordinates: result.turnManeuverCoordinates)
                refreshRoadPolylineCache()
                if isRunningGuidedGeneration {
                    handleGuidedGenerationComplete()
                } else {
                    applyPendingCheckpointRegenerationIfNeeded()
                }
            }
        }
    }

    private func captureInitialEditBaselineIfNeeded() {
        guard editingRouteId == nil, editBaseline == nil else { return }
        editBaseline = RouteEditBaseline.capture(
            name: routeName,
            points: points,
            roadCoordinates: roadCoordinates,
            distanceMeters: distanceMeters,
            travelSeconds: travelSeconds
        )
    }

    private func attemptClose() {
        if hasUnsavedChanges {
            isShowingDiscardChangesAlert = true
        } else {
            dismiss()
        }
    }

    private func syncAutoPathPoints(turnCoordinates: [CLLocationCoordinate2D]) {
        guard roadCoordinates.count >= 2 else { return }
        let autoCoordinates = RouteAutoPathPointGenerator.autoTurnPathCoordinates(
            turnCoordinates: turnCoordinates,
            roadCoordinates: roadCoordinates,
            polylineIndex: roadPolylineIndex
        )
        let preserved = points.filter { !$0.isAutoShape }
        let autoPoints = autoCoordinates.map {
            RouteBuilderPoint(coordinate: $0, type: .path, isAutoGenerated: true)
        }
        points = orderRoutePoints(preserved + autoPoints)
    }

    private func bootstrapAutoPathPointsIfNeeded() {
        guard roadCoordinates.count >= 2, didSnapToRoad else { return }
        guard !points.contains(where: { $0.isAutoShape }) else { return }

        if editingRouteId != nil {
            #if DEBUG
            OttoRouteBuilderDebugLog.autoPathBootstrap(source: "polyline-local")
            #endif
            let turns = RoutePolylineTurnExtractor.turnCoordinates(along: roadCoordinates)
            lastSnapTurnCoordinates = turns
            syncAutoPathPoints(turnCoordinates: turns)
            return
        }

        let routingInput = routingCoordinates()
        guard routingInput.count >= 2 else { return }
        #if DEBUG
        OttoRouteBuilderDebugLog.autoPathBootstrap(source: "directions-api")
        #endif
        Task {
            let result = await RouteRoadSnapper.buildRoute(for: routingInput)
            guard !Task.isCancelled else { return }
            await MainActor.run {
                lastSnapTurnCoordinates = result.turnManeuverCoordinates
                syncAutoPathPoints(turnCoordinates: result.turnManeuverCoordinates)
            }
        }
    }

    private func beginSaveFlow() {
        guard validateSavePreconditions() else { return }
        continueSaveFlowAfterCheckpointDecision()
    }

    private func validateSavePreconditions() -> Bool {
        guard saveIsActive, !isSaving else {
            if isRunningGuidedGeneration {
                errorMessage = "Wait for route generation to finish, then try again."
            } else if isSnapping {
                errorMessage = "Wait for the route to finish snapping to the road, then try again."
            } else if points.count >= 2 && distanceMeters <= 0 {
                errorMessage = "Route distance is still calculating. Try again in a moment."
            } else if distanceMeters < Self.minimumRouteDriveDistanceMeters {
                errorMessage = "Route drive distance must be at least 1,000 feet."
            }
            return false
        }
        return true
    }

    private func continueSaveFlowAfterCheckpointDecision() {
        if editingRouteId == nil {
            let trimmedName = routeName.trimmingCharacters(in: .whitespacesAndNewlines)
            routeNameDraft = trimmedName == "New Route" ? "" : trimmedName
            isShowingRouteNamePrompt = true
        } else {
            Task { await saveRoute(named: routeName) }
        }
    }

    private func attemptSave(named draftName: String) {
        guard validateSavePreconditions() else { return }
        let trimmedName = draftName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedName.isEmpty else { return }
        Task { await saveRoute(named: trimmedName) }
    }

    private func saveRoute(named draftName: String) async {
        guard appState.hasRoutesAccess else {
            errorMessage = "Routes isn’t available for your account yet."
            return
        }
        guard saveIsActive, !isSaving else {
            if isSnapping {
                errorMessage = "Wait for the route to finish snapping to the road, then try again."
            } else if points.count >= 2 && distanceMeters <= 0 {
                errorMessage = "Route distance is still calculating. Try again in a moment."
            } else if distanceMeters < Self.minimumRouteDriveDistanceMeters {
                errorMessage = "Route drive distance must be at least 1,000 feet."
            }
            return
        }
        let trimmedName = draftName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedName.isEmpty else { return }
        let snapped = roadCoordinates.count >= 2 ? roadCoordinates : points.map(\.coordinate)
        let pointDTOs = points
            .filter { !$0.isAutoShape }
            .compactMap { point -> RoutePointDTO? in
                guard Self.coordinate(from: RoutePointDTO(lat: point.coordinate.latitude, lng: point.coordinate.longitude, markerType: point.type.rawValue)) != nil else {
                    return nil
                }
                return RoutePointDTO(
                    lat: point.coordinate.latitude,
                    lng: point.coordinate.longitude,
                    markerType: point.type.rawValue
                )
            }
        let roadDTOs = snapped.compactMap { coordinate -> RoutePointDTO? in
            guard Self.coordinate(from: RoutePointDTO(lat: coordinate.latitude, lng: coordinate.longitude, markerType: RouteBuilderPointType.path.rawValue)) != nil else {
                return nil
            }
            return RoutePointDTO(
                lat: coordinate.latitude,
                lng: coordinate.longitude,
                markerType: RouteBuilderPointType.path.rawValue
            )
        }
        guard pointDTOs.count >= 2 else {
            errorMessage = "Add a start and finish before saving."
            return
        }
        guard roadDTOs.count >= 2 else {
            errorMessage = "Route geometry is still calculating. Try again in a moment."
            return
        }
        isSaving = true
        routeName = trimmedName
        do {
            let savedRoute: SavedRouteDTO
            if let editingRouteId {
                savedRoute = try await APIClient.shared.updateRoute(
                    routeId: editingRouteId,
                    name: routeName,
                    points: pointDTOs,
                    roadCoordinates: roadDTOs,
                    distanceMeters: distanceMeters,
                    etaSeconds: travelSeconds
                )
            } else {
                savedRoute = try await APIClient.shared.createRoute(
                    name: routeName,
                    points: pointDTOs,
                    roadCoordinates: roadDTOs,
                    distanceMeters: distanceMeters,
                    etaSeconds: travelSeconds
                )
            }
            onRouteSaved?(savedRoute)
            if editingRouteId != nil {
                let savedPoints = savedRoute.points.compactMap { dto -> RouteBuilderPoint? in
                    guard let coordinate = Self.coordinate(from: dto),
                          let markerType = dto.markerType,
                          let type = RouteBuilderPointType(rawValue: markerType) else { return nil }
                    return RouteBuilderPoint(coordinate: coordinate, type: type)
                }
                let savedRoadCoordinates = savedRoute.roadCoordinates.compactMap { Self.coordinate(from: $0) }
                editBaseline = RouteEditBaseline.capture(
                    name: savedRoute.name,
                    points: savedPoints,
                    roadCoordinates: savedRoadCoordinates,
                    distanceMeters: savedRoute.distanceMeters,
                    travelSeconds: savedRoute.etaSeconds
                )
            }
            appState.activeToast = AppToast(text: "Route saved", systemImage: "checkmark.circle.fill")
            OttoAnalytics.logRouteSaved()
            resetEditUndoSession()
            dismiss()
        } catch {
            errorMessage = saveRouteErrorMessage(for: error)
        }
        isSaving = false
    }

    private func saveRouteErrorMessage(for error: Error) -> String {
        let ns = error as NSError
        if ns.domain == "OttoAPI" {
            let msg = (ns.userInfo[NSLocalizedDescriptionKey] as? String)?
                .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            if ns.code == 403 {
                return msg.isEmpty ? "Routes isn’t available for your account yet." : msg
            }
            if !msg.isEmpty {
                return msg
            }
        }
        if let urlError = error as? URLError {
            switch urlError.code {
            case .notConnectedToInternet, .networkConnectionLost, .cannotConnectToHost, .timedOut:
                return "Couldn’t save this route. Check your connection and try again."
            default:
                break
            }
        }
        if error is DecodingError {
            return "Couldn’t save this route. The server returned an unexpected response."
        }
        return "Couldn’t save this route. Try again."
    }

    private var routeBuilderEducationDialog: some View {
        OttoEducationDialog(
            onDismissUnconfirmed: {
                dismissRouteEducation()
            },
            hero: { OttoEducationRouteHero() },
            title: routeBuilderLoc("route_builder_education_title"),
            bodyText: routeBuilderLoc("route_builder_education_body"),
            bulletSectionTitle: routeBuilderLoc("route_builder_education_section"),
            bullets: [
                ("map.fill", routeBuilderLoc("route_builder_education_zoom")),
                ("play.fill", routeBuilderLoc("route_builder_education_endpoints")),
                ("arrow.triangle.turn.up.right.diamond", routeBuilderLoc("route_builder_education_turns")),
                ("flag.fill", routeBuilderLoc("route_builder_education_checkpoints")),
            ],
            footer: routeBuilderLoc("route_builder_education_footer"),
            primaryTitle: routeBuilderLoc("route_builder_education_got_it"),
            onPrimary: {
                dismissRouteEducation()
            },
            secondaryTitle: routeBuilderLoc("route_builder_education_not_now")
        )
    }

    private var routeBuilderLocationPrimerDialog: some View {
        OttoEducationDialog(
            allowsUnconfirmedDismiss: false,
            onDismissUnconfirmed: {},
            hero: { OttoEducationLocationHero() },
            title: routeBuilderLoc("route_builder_location_primer_title"),
            bodyText: routeBuilderLoc("route_builder_location_primer_body"),
            bulletSectionTitle: nil,
            bullets: [],
            footer: routeBuilderLoc("route_builder_location_primer_footer"),
            primaryTitle: routeBuilderLoc("route_builder_location_primer_continue"),
            onPrimary: {
                dismissRouteBuilderLocationPrimer(requestAuth: true)
            },
            secondaryTitle: routeBuilderLoc("map_location_primer_not_now")
        )
    }

    private func routeBuilderLoc(_ key: String) -> String {
        NSLocalizedString(key, bundle: .main, value: key, comment: "")
    }

    private func presentRouteBuilderPrimersIfNeeded() {
        guard !showRouteEducation, !showLocationPrimer else { return }
        if !appState.routeBuilderEducationSeen {
            withAnimation(.spring(response: 0.38, dampingFraction: 0.86)) {
                showRouteEducation = true
            }
        } else {
            maybePresentRouteBuilderLocationPrimer()
        }
    }

    private func dismissRouteEducation() {
        guard showRouteEducation else { return }
        appState.acknowledgeRouteBuilderEducation()
        withAnimation(.easeInOut(duration: 0.18)) {
            showRouteEducation = false
        }
        maybePresentRouteBuilderLocationPrimer()
    }

    private func maybePresentRouteBuilderLocationPrimer() {
        guard !showRouteEducation else { return }
        guard !showLocationPrimer else { return }
        guard locationService.authorizationStatus == .notDetermined else {
            applyNewRouteUserLocationIfAvailable()
            return
        }
        withAnimation(.spring(response: 0.38, dampingFraction: 0.86)) {
            showLocationPrimer = true
        }
    }

    private func dismissRouteBuilderLocationPrimer(requestAuth: Bool = false) {
        withAnimation(.easeInOut(duration: 0.18)) {
            showLocationPrimer = false
        }
        if requestAuth {
            locationService.requestPermissionIfNeeded()
            switch locationService.authorizationStatus {
            case .authorizedAlways, .authorizedWhenInUse:
                appState.requestLocationSessionSync()
            default:
                break
            }
        }
        applyNewRouteUserLocationIfAvailable()
    }

    private func bootstrapNewRouteMapCamera() {
        guard editingRouteId == nil else { return }
        appState.requestLocationSessionSync()
        applyNewRouteUserLocationIfAvailable()
    }

    private var isRouteBuilderLocationAuthorized: Bool {
        switch locationService.authorizationStatus {
        case .authorizedAlways, .authorizedWhenInUse:
            return true
        default:
            return false
        }
    }

    private func resolvedUserCoordinateForNewRoute() -> CLLocationCoordinate2D? {
        guard isRouteBuilderLocationAuthorized else { return nil }
        guard let coordinate = locationService.latestSample?.coordinate ?? locationService.lastLocation?.coordinate,
              CLLocationCoordinate2DIsValid(coordinate) else {
            return nil
        }
        return coordinate
    }

    private func applyNewRouteUserLocationIfAvailable() {
        guard editingRouteId == nil else { return }
        guard !didApplyUserLocationRecenter else { return }
        guard let coordinate = resolvedUserCoordinateForNewRoute() else { return }
        recenterRouteBuilderMap(on: coordinate)
        didApplyUserLocationRecenter = true
    }

    private var routeBuilderRecenterButton: some View {
        Button {
            recenterRouteBuilderOnUser()
        } label: {
            Image(systemName: "scope")
                .font(.title3.weight(.bold))
                .foregroundStyle(.white)
                .frame(width: 56, height: 56)
                .background(Color.black.opacity(0.86))
                .clipShape(Circle())
                .overlay(
                    Circle().stroke(Color.white.opacity(0.12), lineWidth: 1)
                )
        }
        .buttonStyle(RouteBuilderFABPressStyle())
        .disabled(resolvedUserCoordinateForNewRoute() == nil)
        .opacity(resolvedUserCoordinateForNewRoute() == nil ? 0.45 : 1)
        .accessibilityLabel(String(localized: "route_builder_recenter_map"))
    }

    private func recenterRouteBuilderOnUser() {
        guard isRouteBuilderLocationAuthorized else { return }
        appState.requestLocationSessionSync()
        guard let coordinate = resolvedUserCoordinateForNewRoute() else { return }
        recenterRouteBuilderMap(on: coordinate)
    }

    private func recenterRouteBuilderMap(on coordinate: CLLocationCoordinate2D) {
        let region = MKCoordinateRegion(center: coordinate, span: Self.newRouteMapSpan)
        mapRegionCache.region = region
        latestObservedCameraRegion = region
        programmaticMapViewport = OttoMapboxCamera.viewport(for: region)
        applyCameraSettle(from: region)
    }

    nonisolated private static func coordinate(from point: RoutePointDTO) -> CLLocationCoordinate2D? {
        let coordinate = CLLocationCoordinate2D(latitude: point.lat, longitude: point.lng)
        guard CLLocationCoordinate2DIsValid(coordinate), point.lat.isFinite, point.lng.isFinite else { return nil }
        return coordinate
    }

    nonisolated private static func centerCoordinate(for coordinates: [CLLocationCoordinate2D]) -> CLLocationCoordinate2D {
        guard !coordinates.isEmpty else {
            return CLLocationCoordinate2D(latitude: 37.7749, longitude: -122.4194)
        }
        let sum = coordinates.reduce((lat: 0.0, lng: 0.0)) { partial, coordinate in
            (partial.lat + coordinate.latitude, partial.lng + coordinate.longitude)
        }
        return CLLocationCoordinate2D(
            latitude: sum.lat / Double(coordinates.count),
            longitude: sum.lng / Double(coordinates.count)
        )
    }

    private static let newRouteMapSpan = MKCoordinateSpan(latitudeDelta: 0.008, longitudeDelta: 0.008)

    private static func markerLODLatitudeDelta(for region: MKCoordinateRegion) -> Double {
        OttoMapboxCamera.visibleLatitudeDeltaDegrees(for: region)
    }

    /// Above ~5 mi visible latitude span — checkpoint, stop, and path markers render as colored dots.
    private static let regionalDotMinLatitudeDelta: CLLocationDistance =
        (5 * RouteAutoCheckpointGenerator.Options.metersPerMile) / 111_000
    /// ~1,000 ft visible latitude span — checkpoint, stop, and path pins scale to full size at or below this.
    private static let secondaryMarkerFullSizeMaxLatitudeDelta: CLLocationDistance = (1_000 * 0.3048) / 111_000
    private static let routeBuilderSubtleMarkerScale: CGFloat = 0.55
    private static let minimumRouteDriveDistanceMeters = 1000.0 * 0.3048
}

private struct RouteBuilderPlacementCrosshair: View {
    private let ringGreen = RouteMapMarkerColors.startAccent
    private let sizeScale: CGFloat = 1.4

    var body: some View {
        ZStack {
            Circle()
                .stroke(Color.black.opacity(0.88), lineWidth: 3 * sizeScale)
                .frame(width: 26 * sizeScale, height: 26 * sizeScale)

            Circle()
                .stroke(Color.white.opacity(0.92), lineWidth: 2 * sizeScale)
                .frame(width: 24 * sizeScale, height: 24 * sizeScale)

            RoundedRectangle(cornerRadius: 1 * sizeScale, style: .continuous)
                .fill(Color.black.opacity(0.88))
                .frame(width: 34 * sizeScale, height: 4 * sizeScale)

            Rectangle()
                .fill(Color.white.opacity(0.95))
                .frame(width: 32 * sizeScale, height: 2 * sizeScale)

            RoundedRectangle(cornerRadius: 1 * sizeScale, style: .continuous)
                .fill(Color.black.opacity(0.88))
                .frame(width: 4 * sizeScale, height: 34 * sizeScale)

            Rectangle()
                .fill(Color.white.opacity(0.95))
                .frame(width: 2 * sizeScale, height: 32 * sizeScale)

            Circle()
                .stroke(Color.black.opacity(0.88), lineWidth: 1.5 * sizeScale)
                .frame(width: 8 * sizeScale, height: 8 * sizeScale)

            Circle()
                .fill(ringGreen)
                .frame(width: 6 * sizeScale, height: 6 * sizeScale)
        }
        .frame(width: 68 * sizeScale, height: 68 * sizeScale)
        .shadow(color: .black.opacity(0.5), radius: 4 * sizeScale, y: 1 * sizeScale)
        .accessibilityLabel("Map placement crosshair")
    }
}
